/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'john' at '9/2/16 7:37 AM' with Gradle 3.0
 *
 * @author john, @date 9/2/16 7:37 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
