/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'john' at '9/2/16 7:37 AM' with Gradle 3.0
 *
 * @author john, @date 9/2/16 7:37 AM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
